package davide.U2_W1_D5_Gest_Pren_Test.exceptions;

public class ItemNotFoundException extends RuntimeException {
    public ItemNotFoundException(long id) {
        super("Il record con id " + id + " non Ã¨ stato trovato!");
    }
}